DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS forums CASCADE;
DROP TABLE IF EXISTS threads CASCADE;
DROP TABLE IF EXISTS posts CASCADE;
DROP TABLE IF EXISTS votes CASCADE;

DROP FUNCTION IF EXISTS update_path();
DROP FUNCTION IF EXISTS update_threads_count();

DROP TRIGGER IF EXISTS path_update_trigger ON posts;
DROP TRIGGER IF EXISTS add_thread_to_forum ON threads;