[all]
  type = "Debug"
  port = "80" 
  serviceName = "forums"

[SQLDataBase]
  Server = "localhost"
  Database = "forums"
  ApplicationName = "service"
  MaxIdleConns = 2
  MaxOpenConns = 2
  ConnMaxLifetime = "5m"

[ServerOpt]
  ReadTimeout = "5s"
  WriteTimeout = "5s"
  IdleTimeout = "5s"